# Generated by Django 4.0.6 on 2022-09-08 22:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_notificationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrequest',
            name='notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notificationrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 0, 2, 31, 298525)),
        ),
    ]
