# Generated by Django 4.0.6 on 2022-09-08 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_notificationrequest_notified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 0, 33, 15, 149676)),
        ),
        migrations.AlterField(
            model_name='notificationrequest',
            name='notified',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
