# Generated by Django 4.0.6 on 2022-08-06 03:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 8, 6, 5, 54, 23, 220638))),
            ],
        ),
    ]
