# Generated by Django 4.0.6 on 2022-08-08 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branches',
            name='address',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branches',
            name='lat',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branches',
            name='long',
            field=models.TextField(default='-'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='branches',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 8, 15, 58, 10, 413041)),
        ),
    ]
