# Generated by Django 4.0.6 on 2022-09-04 19:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_feedbacks_alter_branches_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 21, 45, 6, 724101)),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 21, 45, 6, 724578)),
        ),
    ]
