# Generated by Django 4.0.6 on 2022-09-08 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_branches_date_alter_feedbacks_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branches',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 0, 33, 15, 150370)),
        ),
        migrations.AlterField(
            model_name='feedbacks',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 9, 0, 33, 15, 151369)),
        ),
    ]
